apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rep-ctrl
  labels:
    app: myapp
    run: nginx
spec:
  replicas: 3
  template:  # Pod definition template
    metadata:
      name: myapp-pod
      labels:
        run: nginx
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
--- 

# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: myapp-replicaset
#   labels:
#     app: myapp
#     run: nginx
# spec:
#   # modify replicas according to your case
#   replicas: 5
#   selector:    # Required field in Replicaset
#     matchLabels:
#       run: nginx
#   template:
#     metadata:
#       labels:
#         run: nginx
#     spec:
#       containers:
#       - name: myapp
#         image: nginx
#         ports:
#         - name: web
#           containerPort:  80
#           protocol: TCP
#         env:
#         - name: NGX_VERSION
#           value: 1.16.1
        

