---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: application
spec:
  type: "LoadBalancer"
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 32005
      protocol: TCP
  selector:
    app: myapp
    run: nginx